---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: Coverity

on:
  schedule:
    # Run Coverity daily at midnight
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.repository == 'systemd/systemd'
    env:
      # Set in repo settings -> secrets -> actions
      COVERITY_SCAN_TOKEN:              "${{ secrets.COVERITY_SCAN_TOKEN }}"
      COVERITY_SCAN_NOTIFICATION_EMAIL: "${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}"
    steps:
      - name: Repository checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # Reuse the setup phase of the unit test script to avoid code duplication
      - name: Install build dependencies
        run: |
          sudo -E .github/workflows/unit-tests.sh SETUP
          # TODO: drop after we switch to ubuntu 26.04
          bpftool_binary=$(find /usr/lib/linux-tools/ /usr/lib/linux-tools-* -name 'bpftool' -perm /u=x 2>/dev/null | sort -r | head -n1)
          if [ -n "$bpftool_binary" ]; then
            sudo rm -f /usr/{bin,sbin}/bpftool
            sudo ln -s "$bpftool_binary" /usr/bin/
          fi
      - name: Build & upload the results
        run: tools/coverity.sh
