# Inspired by: https://github.com/stefanbuck/ristorante
# See: https://stefanbuck.com/blog/codeless-contributions-with-github-issue-forms
---

name: Issue labeler
on:
  issues:
    types: [ opened ]

jobs:
  label-component:
    runs-on: ubuntu-22.04

    permissions:
      issues: write

    strategy:
      matrix:
        template: [ bug_report.yml, feature_request.yml ]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd
        with:
          node-version: '16'

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@fc06b2a0adc5ccb7702ab6b641fd8a742a5e9cc0
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Set labels based on component field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@b89eb39b97529bb7596cb4e716485a6d6f7dd74a
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: component
          block-list: |
            other
          token: ${{ secrets.GITHUB_TOKEN }}
